### ISSUE TITLE
python pineapple problems

### ISSUE THREAD

**Issue by vay3t** [735tesla/python-pineapple#2]
i have problems with python pineapple

```
~/python-pineapple$ python cli-pineapple.py 
Traceback (most recent call last):
  File "cli-pineapple.py", line 6, in <module>
    fruit = Pineapple(API_TOKEN)
  File "/home/vay3t/python-pineapple/pineapple/pineapple.py", line 14, in __init__
    moduleClass = self._pineappleModule.__dict__[moduleName].__dict__[moduleName.title()]
KeyError: 'advanced'
```

my code:
``` python
#!/usr/bin/python
from pineapple.pineapple import Pineapple

API_TOKEN = "xxxx...."
fruit = Pineapple(API_TOKEN)
print fruit
```

**Comment by bahaahassanieh** [comment]
i have the same problem , try calling the api manually , her is a well guided documentation to help you  https://wifipineapple.github.io/wifipineapple-wiki//#!api.md

**Comment by vay3t** [comment]
I have also tried manually, but I would like to use the module of python, it would be more practical

**Comment by sundhaug92** [comment]
Which firmware-version are you on?
Do you have any modules installed?
Which pineapple are you targetting?
What OS are you running on?
Which version of python are you using?

**Comment by couchfault** [comment]
This whole library needs an update. I've been pretty busy after officially being brought on @Hak5. This is a project I started in my free time. I'll get around to it at some point after 2.1.0 is officially released. For now, I'm happy to review and merge pull requests I get. Glad to see people are taking advantage of the WiFi Pineapple's API!

**Comment by pect0ral** [comment]
Make sure you're running in a virtualenv and have all the deps installed. I found that
` from pineapple import *` worked best for me. I've also submitted a pull for errors where json could not be decoded because of some garbage characters in the return stream. It's in my repo in case you're using firmware 2.3 and having that issue.

**Comment by vay3t** [comment]
fixed! thx @pect0ral

**Comment by sundhaug92** [comment]
PR ref-ed by @pect0ral is #4
